# Generated by Django 5.2 on 2025-04-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_remove_user_parent_phone_number_user_user_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="degree_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="dept",
        ),
        migrations.RemoveField(
            model_name="user",
            name="roll_no",
        ),
        migrations.RemoveField(
            model_name="user",
            name="student_type",
        ),
        migrations.RemoveField(
            model_name="user",
            name="year",
        ),
    ]
