# Generated by Django 5.2 on 2025-04-22 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=200, verbose_name='Room Number')),
                ('block', models.CharField(max_length=200, verbose_name='Room Block')),
                ('description', models.CharField(max_length=200, verbose_name='Room description')),
                ('is_lab', models.BooleanField(default=False, max_length=200, verbose_name='Is lab?')),
                ('room_type', models.CharField(choices=[('TL', 'Technical Lab'), ('NTL', 'Non-Technical Lab')], default='TL', max_length=200, verbose_name='Room Type')),
                ('room_min_cap', models.IntegerField(default=0, verbose_name='Min. Cap')),
                ('room_max_cap', models.IntegerField(default=0, verbose_name='Max. Cap')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Has Projector?')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Has AC?')),
                ('tech_level', models.CharField(blank=True, default='null', verbose_name='Tech Level')),
                ('maintained_by', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
            ],
        ),
    ]
