# Generated by Django 5.2 on 2025-04-22 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.IntegerField(blank=True, default=0, verbose_name='Batch')),
                ('current_semester', models.IntegerField(blank=True, default=0, verbose_name='Semester')),
                ('student', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user')),
            ],
        ),
    ]
