# Generated by Django 5.2 on 2025-04-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, verbose_name='Room Number')),
                ('block', models.CharField(max_length=10, verbose_name='Block')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_lab', models.BooleanField(default=False, verbose_name='Is Lab')),
                ('room_type', models.CharField(choices=[('Classroom', 'Classroom'), ('Laboratory', 'Laboratory'), ('Seminar Hall', 'Seminar Hall'), ('Conference Room', 'Conference Room')], max_length=50, verbose_name='Room Type')),
                ('room_min_cap', models.IntegerField(default=0, verbose_name='Minimum Capacity')),
                ('room_max_cap', models.IntegerField(default=0, verbose_name='Maximum Capacity')),
                ('has_projector', models.BooleanField(default=False, verbose_name='Has Projector')),
                ('has_ac', models.BooleanField(default=False, verbose_name='Has AC')),
                ('tech_level', models.CharField(choices=[('None', 'None'), ('Basic', 'Basic'), ('Advanced', 'Advanced'), ('High-tech', 'High-tech')], default='None', max_length=50, verbose_name='Technology Level')),
                ('maintained_by_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintained_rooms', to='department.department')),
            ],
        ),
    ]
