# Generated by Django 5.2 on 2025-04-22 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=20, unique=True)),
                ('block', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('Room', 'Room'), ('TL', 'TL'), ('NTL', 'NTL')], max_length=4)),
                ('min_capacity', models.IntegerField(blank=True, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('has_projector', models.BooleanField(default=False)),
                ('has_ac', models.BooleanField(default=False)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='departments.department')),
            ],
        ),
    ]
