# Generated by Django 5.2 on 2025-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="block",
            field=models.CharField(max_length=100, verbose_name="Block"),
        ),
    ]
