# Generated by Django 5.2 on 2025-04-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("NULL", "NULL"),
                    ("TL", "Technical Lab"),
                    ("NTL", "Non-Technical Lab"),
                ],
                default="NULL",
                max_length=200,
                verbose_name="Room Type",
            ),
        ),
    ]
