# Generated by Django 5.2 on 2025-05-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Class Room', 'Class Room'), ('Computer Lab', 'Computer Lab'), ('Core Lab', 'Core Lab')], max_length=50, verbose_name='Room Type'),
        ),
    ]
