# Generated by Django 5.2 on 2025-05-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_room_block'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='green_board',
            field=models.BooleanField(default=False, verbose_name='Green Board'),
        ),
        migrations.AddField(
            model_name='room',
            name='isLcsAvailable',
            field=models.BooleanField(default=False, verbose_name='Is LCS Available'),
        ),
        migrations.AddField(
            model_name='room',
            name='smart_board',
            field=models.BooleanField(default=False, verbose_name='Smart Board'),
        ),
    ]
