# Generated by Django 5.2 on 2025-05-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_alter_room_room_type'),
        ('rooms', '0003_room_green_board_room_islcsavailable_and_more'),
    ]

    operations = [
    ]
