# Generated by Django 5.2 on 2025-05-05 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rooms", "0003_alter_room_room_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="room_type",
            field=models.CharField(
                choices=[
                    ("Class-Room", "Class Room"),
                    ("Computer-Lab", "Computer Lab"),
                    ("Core-Lab", "Core Lab"),
                ],
                max_length=50,
                verbose_name="Room Type",
            ),
        ),
    ]
