# Generated by Django 5.2 on 2025-05-05 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_alter_room_room_type'),
        ('rooms', '0004_merge_20250505_1309'),
    ]

    operations = [
    ]
