# Generated by Django 5.1.7 on 2025-04-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slot_name",
                    models.CharField(max_length=20, verbose_name="Slot Name"),
                ),
                ("slot_start_time", models.TimeField(verbose_name="Slot Start Time")),
                ("slot_end_time", models.TimeField(verbose_name="Slot End Time")),
            ],
        ),
    ]
