# Generated by Django 5.2 on 2025-04-30 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0001_initial'),
        ('teacher', '0005_teacher_is_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSlotAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], verbose_name='Day of Week')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='slot.slot')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_assignments', to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Slot Assignment',
                'verbose_name_plural': 'Teacher Slot Assignments',
                'ordering': ['day_of_week', 'slot__slot_start_time'],
                'constraints': [models.UniqueConstraint(fields=('teacher', 'slot', 'day_of_week'), name='unique_teacher_slot_assignment')],
            },
        ),
    ]
