# Generated by Django 5.2 on 2025-04-30 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0002_teacherslotassignment'),
        ('teacher', '0006_placeholderproxy_teacherresigingproxy'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='teacherslotassignment',
            constraint=models.UniqueConstraint(fields=('teacher', 'day_of_week'), name='one_slot_per_teacher_per_day'),
        ),
    ]
