# Generated by Django 5.2 on 2025-05-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0003_teacherslotassignment_one_slot_per_teacher_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacherslotassignment',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday')], verbose_name='Day of Week'),
        ),
    ]
