# Generated by Django 5.2 on 2025-05-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slot', '0004_alter_teacherslotassignment_day_of_week'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='slot_type',
            field=models.CharField(choices=[('A', 'Slot A (8AM - 3PM)'), ('B', 'Slot B (10AM - 5PM)'), ('C', 'Slot C (12PM - 7PM)')], default='A', max_length=1, verbose_name='Slot Type'),
        ),
    ]
