# Generated by Django 5.1.7 on 2025-05-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0005_slot_slot_type"),
        ("teacher", "0008_alter_teacher_teacher_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherslotassignment",
            options={
                "ordering": ["day_of_week", "slot_type"],
                "verbose_name": "Teacher Slot Assignment",
                "verbose_name_plural": "Teacher Slot Assignments",
            },
        ),
        migrations.RemoveConstraint(
            model_name="teacherslotassignment",
            name="unique_teacher_slot_assignment",
        ),
        migrations.RemoveField(
            model_name="teacherslotassignment",
            name="slot",
        ),
        migrations.AddField(
            model_name="teacherslotassignment",
            name="slot_type",
            field=models.CharField(
                choices=[
                    ("A", "Slot A (8AM - 3PM)"),
                    ("B", "Slot B (10AM - 5PM)"),
                    ("C", "Slot C (12PM - 7PM)"),
                ],
                default="A",
                max_length=1,
                verbose_name="Slot Type",
            ),
        ),
        migrations.AlterField(
            model_name="teacherslotassignment",
            name="day_of_week",
            field=models.IntegerField(
                choices=[
                    (0, "Monday"),
                    (1, "Tuesday"),
                    (2, "Wednesday"),
                    (3, "Thursday"),
                    (4, "Friday"),
                    (5, "Saturday"),
                    (6, "Sunday"),
                ],
                verbose_name="Day of Week",
            ),
        ),
        migrations.AddConstraint(
            model_name="teacherslotassignment",
            constraint=models.UniqueConstraint(
                fields=("teacher", "slot_type", "day_of_week"),
                name="unique_teacher_slot_assignment",
            ),
        ),
    ]
