# Generated by Django 5.2 on 2025-05-05 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0006_alter_teacherslotassignment_options_and_more"),
        ("teacher", "0008_alter_teacher_teacher_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacherslotassignment",
            options={
                "ordering": ["day_of_week", "slot__slot_start_time"],
                "verbose_name": "Teacher Slot Assignment",
                "verbose_name_plural": "Teacher Slot Assignments",
            },
        ),
        migrations.RemoveConstraint(
            model_name="teacherslotassignment",
            name="unique_teacher_slot_assignment",
        ),
        migrations.RemoveField(
            model_name="teacherslotassignment",
            name="slot_type",
        ),
        migrations.AddField(
            model_name="teacherslotassignment",
            name="slot",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher_assignments",
                to="slot.slot",
            ),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="teacherslotassignment",
            constraint=models.UniqueConstraint(
                fields=("teacher", "slot", "day_of_week"),
                name="unique_teacher_slot_assignment",
            ),
        ),
    ]
