# Generated by Django 5.2 on 2025-04-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=200, verbose_name='Course Code')),
                ('course_name', models.CharField(max_length=200, verbose_name='Course Name')),
                ('course_year', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Course Year')),
                ('course_semester', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=1, verbose_name='Course Semester')),
                ('regulation', models.CharField(max_length=200, verbose_name='Regulation')),
                ('course_type', models.CharField(blank=True, choices=[('T', 'Theory'), ('L', 'Lab'), ('LoT', 'Lab And Theory')], default='T', max_length=50, verbose_name='Course Type')),
                ('lecture_hours', models.IntegerField(blank=True, default=0, verbose_name='Lecture Hours')),
                ('tutorial_hours', models.IntegerField(blank=True, default=0, verbose_name='Tutorial Hours')),
                ('practical_hours', models.IntegerField(blank=True, default=0, verbose_name='Practical Hours')),
                ('credits', models.IntegerField(default=0, verbose_name='Course Credit')),
                ('department', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
            ],
            options={
                'unique_together': {('department', 'course_code', 'course_semester')},
            },
        ),
    ]
