# Generated by Django 5.1.7 on 2025-04-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
        ("rooms", "0001_initial"),
        ("slot", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseroompreference",
            name="room_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rooms.room"
            ),
        ),
        migrations.AddField(
            model_name="courseslotpreference",
            name="course_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="slot_preferences",
                to="course.course",
            ),
        ),
        migrations.AddField(
            model_name="courseslotpreference",
            name="slot_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="slot.slot"
            ),
        ),
    ]
