# Generated by Django 5.2 on 2025-04-29 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="course_type",
        ),
        migrations.RemoveField(
            model_name="course",
            name="credits",
        ),
        migrations.RemoveField(
            model_name="course",
            name="is_zero_credit_course",
        ),
        migrations.RemoveField(
            model_name="course",
            name="lecture_hours",
        ),
        migrations.RemoveField(
            model_name="course",
            name="no_of_students",
        ),
        migrations.RemoveField(
            model_name="course",
            name="practical_hours",
        ),
        migrations.RemoveField(
            model_name="course",
            name="regulation",
        ),
        migrations.RemoveField(
            model_name="course",
            name="tutorial_hours",
        ),
    ]
