# Generated by Django 5.2 on 2025-04-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0001_initial"),
        ("department", "0002_alter_department_hod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                max_length=200,
                on_delete=django.db.models.deletion.CASCADE,
                to="department.department",
            ),
        ),
    ]
