# Generated by Django 5.2 on 2025-04-29 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_remove_course_course_type_remove_course_credits_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TeacherCourseAssignment",
        ),
    ]
