# Generated by Django 5.1.7 on 2025-04-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_teachercourseassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="courseroompreference",
            name="lab_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Lab Description"
            ),
        ),
        migrations.AddField(
            model_name="courseroompreference",
            name="lab_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("low-end", "Low-End - For programming and basic coding"),
                    ("mid-end", "Mid-End - For OS and computation-intensive subjects"),
                    (
                        "high-end",
                        "High-End - For ML, NLP, and resource-intensive subjects",
                    ),
                ],
                max_length=50,
                null=True,
                verbose_name="Lab Type",
            ),
        ),
    ]
