# Generated by Django 5.1.7 on 2025-04-28 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_courseroompreference_lab_description_and_more"),
        ("rooms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="courseroompreference",
            name="room_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="rooms.room",
            ),
        ),
    ]
