# Generated by Django 5.2 on 2025-04-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0004_alter_course_department"),
        ("department", "0002_alter_department_hod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.ForeignKey(
                max_length=200,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="department.department",
            ),
        ),
    ]
