# Generated by Django 5.2 on 2025-04-23 19:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_course_description_course_course_teacher_and_more'),
        ('department', '0003_remove_department_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='course_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_teacher',
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
    ]
