# Generated by Django 5.2 on 2025-04-24 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_course_description_and_more'),
        ('department', '0004_department_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='elective_type',
            field=models.CharField(blank=True, choices=[('NE', 'Non-Elective'), ('PE', 'Professional Elective'), ('OE', 'Open Elective')], default='NE', max_length=50, verbose_name='Elective Type'),
        ),
        migrations.AddField(
            model_name='course',
            name='offered_to',
            field=models.ManyToManyField(blank=True, related_name='available_courses', to='department.department'),
        ),
    ]
