# Generated by Django 5.2 on 2025-04-24 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_course_elective_type_course_offered_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lab_pref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lab Preference'),
        ),
        migrations.AddField(
            model_name='course',
            name='lab_type',
            field=models.CharField(blank=True, choices=[('NULL', 'NULL'), ('TL', 'Technical Lab'), ('NTL', 'Non-Technical Lab')], default='NULL', null=True, verbose_name='Lab Type'),
        ),
    ]
