# Generated by Django 5.2 on 2025-04-24 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_course_lab_pref_course_lab_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='no_of_students',
            field=models.IntegerField(default=0, verbose_name='No. of students'),
        ),
    ]
