# Generated by Django 5.2 on 2025-04-24 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_course_no_of_students'),
        ('courseMaster', '0001_initial'),
        ('department', '0004_department_hod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'course', 'course_semester', 'managed_by')},
        ),
        migrations.AddField(
            model_name='course',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='courseMaster.coursemaster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='managed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_courses', to='department.department'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_year',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Course Year'),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='department.department'),
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_code',
        ),
        migrations.RemoveField(
            model_name='course',
            name='course_name',
        ),
        migrations.RemoveField(
            model_name='course',
            name='offered_to',
        ),
    ]
