# # Generated by Django 5.2 on 2025-04-24 13:07

# from django.db import migrations


# class Migration(migrations.Migration):

#     dependencies = [
#         ('course', '0011_alter_course_unique_together_course_course_and_more'),
#     ]

#     operations = [
#     ]
from django.db import migrations

class Migration(migrations.Migration):
    dependencies = [
        ('course', '0011_alter_course_unique_together_course_course_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'course', 'course_semester', 'managed_by')},
        ),
    ]