# Generated by Django 5.2 on 2025-04-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20250424_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.CharField(default='New Course', max_length=300, verbose_name='Course Name'),
        ),
    ]
