# Generated by Django 5.2 on 2025-04-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_alter_course_course'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
    ]
