# Generated by Django 5.2 on 2025-04-24 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_alter_course_unique_together'),
        ('courseMaster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courseMaster.coursemaster'),
        ),
    ]
