# Generated by Django 5.2 on 2025-04-24 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_alter_course_course'),
        ('courseMaster', '0001_initial'),
        ('department', '0004_department_hod'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('department', 'course', 'course_semester', 'managed_by')},
        ),
    ]
