# Generated by Django 5.2 on 2025-04-25 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_alter_course_unique_together'),
        ('courseMaster', '0001_initial'),
        ('department', '0004_department_hod'),
        ('rooms', '0002_alter_room_maintained_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course', 'course_semester', 'managed_by')},
        ),
        migrations.RemoveField(
            model_name='course',
            name='department',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lab_pref',
        ),
        migrations.AddField(
            model_name='course',
            name='lab_pref',
            field=models.ManyToManyField(blank=True, related_name='preferred_courses', to='rooms.room'),
        ),
    ]
