# Generated by Django 5.2 on 2025-04-25 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_alter_course_unique_together_and_more'),
        ('courseMaster', '0001_initial'),
        ('department', '0004_department_hod'),
        ('rooms', '0002_alter_room_maintained_by'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='course',
            name='for_dept',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='department.department'),
        ),
        migrations.AddField(
            model_name='course',
            name='need_assist_teacher',
            field=models.BooleanField(default=False, verbose_name='Assist teacher?'),
        ),
        migrations.AlterField(
            model_name='course',
            name='lab_pref',
            field=models.ManyToManyField(blank=True, related_name='lab_prefference', to='rooms.room'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('course', 'course_semester', 'for_dept', 'managed_by')},
        ),
    ]
