# Generated by Django 5.2 on 2025-04-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_alter_course_unique_together_course_for_dept_and_more'),
        ('slot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_zero_credit_course',
            field=models.BooleanField(default=False, verbose_name='Is Zero Credit Course?'),
        ),
        migrations.AddField(
            model_name='course',
            name='slot_prefference',
            field=models.ManyToManyField(blank=True, null=True, to='slot.slot'),
        ),
    ]
