# Generated by Django 5.2 on 2025-04-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_parent_phone_number_user_user_type'),
        ('department', '0002_department_hod'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_role',
            field=models.CharField(default='Professor', max_length=200, verbose_name='Teacher Role'),
        ),
        migrations.AlterUniqueTogether(
            name='teacher',
            unique_together={('teacher', 'dept', 'staff_code')},
        ),
    ]
