# Generated by Django 5.2 on 2025-05-16 19:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('slot', '0001_initial'),
        ('teacherCourse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('is_recurring', models.BooleanField(default=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('session_type', models.CharField(choices=[('Lecture', 'Lecture'), ('Lab', 'Laboratory'), ('Tutorial', 'Tutorial')], max_length=20)),
                ('course_assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherCourse.teachercourse')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slot.slot')),
            ],
            options={
                'db_table': 'timetable',
                'unique_together': {('day_of_week', 'slot', 'room')},
            },
        ),
        migrations.CreateModel(
            name='TimetableChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_day_of_week', models.IntegerField(blank=True, choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], null=True)),
                ('reason', models.TextField()),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('new_room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room')),
                ('new_slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='slot.slot')),
                ('original_timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='timetable.timetable')),
            ],
            options={
                'db_table': 'timetable_change',
            },
        ),
        migrations.CreateModel(
            name='TimetableGenerationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('max_teacher_slots_per_day', models.IntegerField(default=5)),
                ('enable_lunch_breaks', models.BooleanField(default=True)),
                ('enable_lab_consecutive', models.BooleanField(default=True)),
                ('enable_student_conflicts', models.BooleanField(default=True)),
                ('enable_staggered_schedule', models.BooleanField(default=False)),
                ('min_course_instances', models.IntegerField(default=1)),
                ('division_assignment', models.CharField(choices=[('A', 'Division A (8 AM - 3 PM)'), ('B', 'Division B (10 AM - 5 PM)'), ('C', 'Division C (12 PM - 7 PM)')], default='A', max_length=1)),
                ('solver_timeout', models.IntegerField(default=600)),
                ('is_generated', models.BooleanField(default=False)),
                ('generation_started_at', models.DateTimeField(blank=True, null=True)),
                ('generation_completed_at', models.DateTimeField(blank=True, null=True)),
                ('generation_log', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'timetable_generation_config',
            },
        ),
    ]
