# Generated by Django 5.2 on 2025-04-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(default=0, verbose_name='Student Count')),
                ('academic_year', models.IntegerField(default=0, verbose_name='Acd. year')),
                ('semester', models.IntegerField(default=0, verbose_name='Semester')),
                ('course', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('teacher', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
            ],
        ),
    ]
