# Generated by Django 5.2 on 2025-04-28 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50, verbose_name='Course ID')),
                ('course_name', models.CharField(max_length=255, verbose_name='Course Name')),
                ('is_zero_credit_course', models.BooleanField(default=False, verbose_name='Is Zero Credit Course?')),
                ('lecture_hours', models.IntegerField(default=0, verbose_name='Lecture Hours')),
                ('practical_hours', models.IntegerField(default=0, verbose_name='Practical Hours')),
                ('tutorial_hours', models.IntegerField(default=0, verbose_name='Tutorial Hours')),
                ('credits', models.IntegerField(default=0, verbose_name='Course Credit')),
                ('regulation', models.CharField(default=0, max_length=50, verbose_name='Regulation')),
                ('course_type', models.CharField(choices=[('T', 'Theory'), ('L', 'Lab'), ('LoT', 'Lab And Theory')], default='T', max_length=50, verbose_name='Course Type')),
                ('course_dept_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_master', to='department.department')),
            ],
        ),
    ]
