# Generated by Django 5.1.7 on 2025-04-26 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_id",
                    models.CharField(max_length=50, verbose_name="Course ID"),
                ),
                (
                    "course_name",
                    models.CharField(max_length=255, verbose_name="Course Name"),
                ),
                (
                    "course_dept_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_master",
                        to="department.department",
                    ),
                ),
            ],
        ),
    ]
