# Generated by Django 5.2 on 2025-04-28 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseMaster", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursemaster",
            name="course_type",
            field=models.CharField(
                choices=[("T", "Theory"), ("L", "Lab"), ("LoT", "Lab And Theory")],
                default="T",
                max_length=50,
                verbose_name="Course Type",
            ),
        ),
        migrations.AddField(
            model_name="coursemaster",
            name="credits",
            field=models.IntegerField(default=0, verbose_name="Course Credit"),
        ),
        migrations.AddField(
            model_name="coursemaster",
            name="is_zero_credit_course",
            field=models.BooleanField(
                default=False, verbose_name="Is Zero Credit Course?"
            ),
        ),
        migrations.AddField(
            model_name="coursemaster",
            name="lecture_hours",
            field=models.IntegerField(default=0, verbose_name="Lecture Hours"),
        ),
        migrations.AddField(
            model_name="coursemaster",
            name="practical_hours",
            field=models.IntegerField(default=0, verbose_name="Practical Hours"),
        ),
        migrations.AddField(
            model_name="coursemaster",
            name="regulation",
            field=models.CharField(default=0, max_length=50, verbose_name="Regulation"),
        ),
        migrations.AddField(
            model_name="coursemaster",
            name="tutorial_hours",
            field=models.IntegerField(default=0, verbose_name="Tutorial Hours"),
        ),
    ]
