# Generated by Django 5.2 on 2025-05-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courseMaster", "0003_alter_coursemaster_degree_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursemaster",
            name="degree_type",
            field=models.CharField(
                choices=[
                    ("BE", "Bachelor of Engineering"),
                    ("BTECH", "Bachelor of Technology"),
                    ("ME", "Master of Engineering"),
                    ("MTECH", "Master of Technology"),
                    ("MBA", "Master of Business Administration"),
                    ("MCA", "Master of Computer Applications"),
                ],
                default="BE",
                verbose_name="Degree Type",
            ),
        ),
    ]
