# Generated by Django 5.2 on 2025-04-22 11:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_code', models.CharField(blank=True, max_length=200, verbose_name='Staff Code')),
                ('teacher_specialisation', models.CharField(blank=True, default='', max_length=100, verbose_name='Specialisation')),
                ('teacher_working_hours', models.IntegerField(default=21, verbose_name='Working Hour')),
                ('dept', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='department.department')),
                ('teacher', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user')),
            ],
        ),
    ]
