# Generated by Django 5.2 on 2025-04-22 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_user_parent_phone_number_user_user_type'),
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, default=1, max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='authentication.user'),
            preserve_default=False,
        ),
    ]
