# Generated by Django 5.2 on 2025-04-23 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_department_hod"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="department",
            unique_together={("dept_name",)},
        ),
    ]
