# Generated by Django 5.1.7 on 2025-04-23 03:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="student",
            options={"verbose_name": "Student", "verbose_name_plural": "Students"},
        ),
        migrations.AlterField(
            model_name="student",
            name="batch",
            field=models.IntegerField(default=0, verbose_name="Batch"),
        ),
        migrations.AlterField(
            model_name="student",
            name="current_semester",
            field=models.IntegerField(default=1, verbose_name="Semester"),
        ),
        migrations.AlterUniqueTogether(
            name="student",
            unique_together={("student", "batch")},
        ),
    ]
