# Generated by Django 5.2 on 2025-04-23 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0003_alter_department_unique_together"),
        ("student", "0002_alter_student_options_alter_student_batch_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="degree_type",
            field=models.CharField(
                choices=[("UG", "Undergraduate"), ("PG", "Postgraduate")],
                default="UG",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="dept",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="department.department",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_no",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Roll No"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="student_type",
            field=models.CharField(
                choices=[("Mgmt", "Management"), ("Govt", "Government")],
                default="Mgmt",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="year",
            field=models.IntegerField(default=0, verbose_name="Year"),
        ),
        migrations.AlterField(
            model_name="student",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
