# Generated by Django 5.1.7 on 2025-04-26 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("department", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "staff_code",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Staff Code"
                    ),
                ),
                (
                    "teacher_role",
                    models.CharField(
                        choices=[
                            ("Professor", "Professor"),
                            ("Asst. Professor", "Asst. Professor"),
                            ("HOD", "HOD"),
                            ("DC", "DC"),
                        ],
                        default="Professor",
                        max_length=100,
                        verbose_name="Teacher Role",
                    ),
                ),
                (
                    "teacher_specialisation",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Specialisation"
                    ),
                ),
                (
                    "teacher_working_hours",
                    models.IntegerField(default=21, verbose_name="Working Hour"),
                ),
                (
                    "dept_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="department_teachers",
                        to="department.department",
                    ),
                ),
                (
                    "teacher_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
