# Generated by Django 5.2 on 2025-04-23 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("department", "0002_alter_department_hod"),
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="dept",
            field=models.ForeignKey(
                max_length=200,
                on_delete=django.db.models.deletion.PROTECT,
                to="department.department",
            ),
        ),
    ]
