# Generated by Django 5.2 on 2025-04-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="availability_type",
            field=models.CharField(
                choices=[
                    ("regular", "Regular (All Working Days)"),
                    ("limited", "Limited (Specific Days/Times)"),
                ],
                default="regular",
                max_length=20,
                verbose_name="Availability Type",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="company_name",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Company/Organization",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="is_industry_professional",
            field=models.BooleanField(
                default=False, verbose_name="Industry Professional"
            ),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_role",
            field=models.CharField(
                choices=[
                    ("Professor", "Professor"),
                    ("Asst. Professor", "Asst. Professor"),
                    ("HOD", "HOD"),
                    ("DC", "DC"),
                    ("Industry Professional", "Industry Professional"),
                ],
                default="Professor",
                max_length=100,
                verbose_name="Teacher Role",
            ),
        ),
        migrations.CreateModel(
            name="TeacherAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Start Time")),
                ("end_time", models.TimeField(verbose_name="End Time")),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_slots",
                        to="teacher.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Teacher Availability",
                "verbose_name_plural": "Teacher Availabilities",
                "ordering": ["day_of_week", "start_time"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("teacher", "day_of_week", "start_time", "end_time"),
                        name="unique_teacher_availability_slot",
                    )
                ],
            },
        ),
    ]
