# Generated by Django 5.1.7 on 2025-04-29 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_availability_type_teacher_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacher",
            name="teacher_role",
            field=models.CharField(
                choices=[
                    ("Professor", "Professor"),
                    ("Asst. Professor", "Asst. Professor"),
                    ("HOD", "HOD"),
                    ("DC", "DC"),
                    ("POP", "Professor of Practice"),
                    ("Industry Professional", "Industry Professional"),
                ],
                default="Professor",
                max_length=100,
                verbose_name="Teacher Role",
            ),
        ),
    ]
