# Generated by Django 5.1.7 on 2025-04-23 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0002_teacher_teacher_role_alter_teacher_unique_together"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name": "Teacher", "verbose_name_plural": "Teachers"},
        ),
        migrations.AlterField(
            model_name="teacher",
            name="teacher_role",
            field=models.CharField(
                choices=[
                    ("Professor", "Professor"),
                    ("Asst. Professor", "Asst. Professor"),
                    ("HOD", "HOD"),
                    ("DC", "DC"),
                ],
                default="Professor",
                max_length=200,
                verbose_name="Teacher Role",
            ),
        ),
    ]
