# Generated by Django 5.1.7 on 2025-04-29 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0003_alter_teacher_teacher_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="teacher",
            name="company_name",
        ),
    ]
