# Generated by Django 5.2 on 2025-04-23 19:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_remove_department_hod'),
        ('teacher', '0003_alter_teacher_dept'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.PROTECT, to='department.department'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher',
            field=models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
