# Generated by Django 5.2 on 2025-04-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_remove_teacher_company_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="teacher",
            name="is_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="Placeholder for future recruitment",
                verbose_name="Is Placeholder",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="placeholder_description",
            field=models.TextField(
                blank=True,
                help_text="Requirements for the position",
                verbose_name="Placeholder Description",
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="resignation_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Resignation Date"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="resignation_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("resigning", "Resigning/Notice Period"),
                    ("resigned", "Resigned"),
                ],
                default="active",
                max_length=20,
                verbose_name="Resignation Status",
            ),
        ),
    ]
