# Generated by Django 5.2 on 2025-04-30 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_teacher_is_placeholder_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceholderProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Placeholders',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teacher.teacher',),
        ),
        migrations.CreateModel(
            name='TeacherResigingProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Resigning Teacher',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('teacher.teacher',),
        ),
    ]
