# Generated by Django 5.2 on 2025-05-03 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_placeholderproxy_teacherresigingproxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_role',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Asst. Professor', 'Asst. Professor'), ('HOD', 'Head of Department'), ('DC', 'DC'), ('POP', 'Professor of Practice'), ('Industry Professional', 'Industry Professional'), ('Dean', 'Dean'), ('Admin', 'Admin'), ('Vice Principal', 'Vice Principal'), ('Principal', 'Principal'), ('Physical Director', 'Physical Director')], default='Professor', max_length=100, verbose_name='Teacher Role'),
        ),
    ]