# Generated by Django 5.2 on 2025-05-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0008_alter_teacher_teacher_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_role',
            field=models.CharField(choices=[('HOD', 'Head of Department'), ('Professor', 'Professor'), ('Professor and HOD', 'Professor and HOD'), ('Professor and Dean', 'Professor and Dean'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor', 'Assistant Professor'), ('Assistant Professor SG', 'Assistant Professor (SG)'), ('Assistant Professor SS', 'Assistant Professor (SS)'), ('AP SS Coordin PG Studies', 'AP SS Coordinator PG Studies'), ('Adjunct Faculty', 'Adjunct Faculty'), ('Professor of Practice', 'Professor of Practice'), ('Professor And Academic Head', 'Professor and Academic Head'), ('Professor and Director - Alumni Affairs', 'Professor and Director - Alumni Affairs'), ('Director And HOD', 'Director and HOD'), ('System Administrator', 'System Administrator'), ('AOP And HOD', 'AOP and HOD'), ('Professor and Dean (Academics)', 'Professor and Dean (Academics)'), ('Director -Startup HQ', 'Director - Startup HQ'), ('Assistant Professor Cum CSRC Coordinator', 'Assistant Professor Cum CSRC Coordinator'), ('Teaching Assistant', 'Teaching Assistant'), ('Assistant Professor POP', 'Assistant Professor POP'), ('Professor and PG Director', 'Professor and PG Director'), ('Professor and Research Head', 'Professor and Research Head'), ('Professor - Postgraduate Studies', 'Professor - Postgraduate Studies'), ('Professor and Admin Office', 'Professor and Admin Office'), ('Dean Student Affairs', 'Dean Student Affairs'), ('AOP Academic Head', 'AOP Academic Head'), ('Professor and Controller of Examinations', 'Professor and Controller of Examinations'), ('Principal and Professor', 'Principal and Professor'), ('Selection Grade Lecturer', 'Selection Grade Lecturer'), ('Assistant Professor - Product Associate', 'Assistant Professor - Product Associate'), ('Director - Research & Publications', 'Director - Research & Publications'), ('Vice Principal', 'Vice Principal'), ('Physical Director', 'Physical Director'), ('Industry Professional', 'Industry Professional')], default='Professor', max_length=100, verbose_name='Teacher Role'),
        ),
    ]
