# Generated by Django 5.2 on 2025-04-23 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_count', models.IntegerField(default=0, verbose_name='Student Count')),
                ('academic_year', models.IntegerField(default=0, verbose_name='Acd. year')),
                ('semester', models.IntegerField(default=0, verbose_name='Semester')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='course.course')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='teacher.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Course Assignment',
                'verbose_name_plural': 'Teacher Course Assignments',
                'unique_together': {('teacher', 'course', 'semester')},
            },
        ),
    ]
