# Generated by Django 5.2 on 2025-04-28 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_teachercourseassignment"),
        ("teacher", "0001_initial"),
        ("teacherCourse", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teachercourse",
            unique_together={("teacher_id", "course_id")},
        ),
    ]
