# Generated by Django 5.2 on 2025-04-29 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("slot", "0001_initial"),
        ("teacherCourse", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercourse",
            name="requires_special_scheduling",
            field=models.BooleanField(
                default=False, verbose_name="Requires Special Scheduling"
            ),
        ),
        migrations.CreateModel(
            name="IndustryProfessionalSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.IntegerField(
                        choices=[
                            (0, "Monday"),
                            (1, "Tuesday"),
                            (2, "Wednesday"),
                            (3, "Thursday"),
                            (4, "Friday"),
                            (5, "Saturday"),
                            (6, "Sunday"),
                        ],
                        verbose_name="Day of Week",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Confirmation"),
                            ("confirmed", "Confirmed"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, null=True, verbose_name="Notes"),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="slot.slot"
                    ),
                ),
                (
                    "teacher_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_schedules",
                        to="teacherCourse.teachercourse",
                    ),
                ),
            ],
            options={
                "verbose_name": "Industry Professional Schedule",
                "verbose_name_plural": "Industry Professional Schedules",
                "unique_together": {("teacher_course", "day_of_week", "slot")},
            },
        ),
    ]
