# Generated by Django 5.1.7 on 2025-04-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_course_course_semester_and_more"),
        ("teacher", "0003_alter_teacher_options_alter_teacher_teacher_role"),
        ("teacherCourse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="teachercourse",
            options={
                "verbose_name": "Teacher Course Assignment",
                "verbose_name_plural": "Teacher Course Assignments",
            },
        ),
        migrations.AlterField(
            model_name="teachercourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="course.course"
            ),
        ),
        migrations.AlterField(
            model_name="teachercourse",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="teacher.teacher"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="teachercourse",
            unique_together={("teacher", "course", "semester")},
        ),
    ]
