# Generated by Django 5.1.7 on 2025-04-29 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacher", "0004_remove_teacher_company_name"),
        ("teacherCourse", "0002_teachercourse_requires_special_scheduling_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercourse",
            name="preferred_availability_slots",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses_scheduled",
                to="teacher.teacheravailability",
                verbose_name="Preferred Availability Slots",
            ),
        ),
        migrations.DeleteModel(
            name="IndustryProfessionalSchedule",
        ),
    ]
