# Generated by Django 5.1.7 on 2025-04-30 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teacherCourse", "0003_teachercourse_preferred_availability_slots_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="teachercourse",
            name="is_assistant",
            field=models.BooleanField(
                default=False, verbose_name="Is Assistant Teacher"
            ),
        ),
    ]
