# Generated by Django 5.2 on 2025-05-06 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherCourse', '0004_teachercourse_is_assistant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='teachercourse',
            unique_together=set(),
        ),
    ]
