# Generated by Django 5.2 on 2025-04-22 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='course.course')),
                ('student', models.ForeignKey(max_length=200, on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
