# Generated by Django 5.1.7 on 2025-04-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0003_alter_course_course_semester_and_more"),
        ("student", "0002_alter_student_options_alter_student_batch_and_more"),
        ("studentCourse", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studentcourse",
            options={
                "verbose_name": "Student Course Enrollment",
                "verbose_name_plural": "Student Course Enrollments",
            },
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="course.course"
            ),
        ),
        migrations.AlterField(
            model_name="studentcourse",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="student.student"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="studentcourse",
            unique_together={("student", "course")},
        ),
    ]
